/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package MVCProj000.Anno.LayeredApp.Emp

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
public class MVCProj000AnnoLayeredAppEmpPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'MVCProj000.Anno.LayeredApp.Emp.greeting'")
            }
        }
    }
}
