/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package MVCProj000.Anno.LayeredApp.Emp

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'MVCProj000.Anno.LayeredApp.Emp.greeting' plugin.
 */
public class MVCProj000AnnoLayeredAppEmpPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("MVCProj000.Anno.LayeredApp.Emp.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
